services:
  libreria:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: ${DB_SOURCE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PRIVATE_KEY: ${PRIVATE_KEY}
      USER_GENERATOR: ${USER_GENERATOR}
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: libreria
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  db_data: